"""
Mining Company Portal - Customized for Gold Fields
"""
import streamlit as st

# === SECURITY CHECK ===
if not st.session_state.get('authenticated', False):
    st.error("🔒 Authentication required")
    st.stop()

if not st.session_state.get('show_mining_portal', False):
    st.error("⛔ Access Denied: Mining portal is exclusive to mining company clients")
    st.info("Please contact Guardian Ghana for mining client access")
    st.stop()

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import numpy as np
import base64
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

st.set_page_config(
    page_title="Mining Operations Portal - Guardian Ghana",
    page_icon="⛏️",
    layout="wide"
)

# Professional styling
st.markdown("""
<style>
.mining-section {
    padding: 1.5rem;
    margin: 1rem 0;
    border-radius: 10px;
    border-left: 5px solid #d4af37;
    background-color: #f8f9fa;
}
.compliance-card {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 1.5rem;
    border-radius: 10px;
    margin: 1rem 0;
}
.risk-metric {
    font-size: 2.5rem;
    font-weight: bold;
    text-align: center;
}
.pdf-button {
    background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
    color: white;
    padding: 0.8rem 1.5rem;
    border-radius: 8px;
    border: none;
    font-weight: bold;
    font-size: 1rem;
}
.pdf-button:hover {
    background: linear-gradient(135deg, #2a5298 0%, #1e3c72 100%);
    transform: scale(1.02);
}
</style>
""", unsafe_allow_html=True)

# Header
col1, col2, col3 = st.columns([3, 1, 1])
with col1:
    st.title("⛏️ Mining Operations Portal")
    st.markdown("### Gold Fields Ghana - Environmental Monitoring Dashboard")
with col2:
    st.image("https://cdn-icons-png.flaticon.com/512/3067/3067256.png", width=80)
with col3:
    st.metric("🟢 Status", "Online", delta="All Systems Normal")

st.markdown("---")

# Mine Selection
st.sidebar.header("🏭 Mine Selection")
selected_mine = st.sidebar.selectbox(
    "Choose Mining Operation:",
    ["Tarkwa Gold Mine", "Damang Gold Mine", "Both Operations"],
    index=0
)

# Date Range
st.sidebar.header("📅 Date Range")
date_range = st.sidebar.date_input(
    "Select Period:",
    [datetime.now().date() - timedelta(days=30), datetime.now().date()]
)

# === PDF GENERATION FUNCTIONS ===
def generate_epa_pdf(selected_mine, compliance_rate, avg_turbidity, avg_ph, incidents, mining_data):
    """Generate a professional EPA compliance report PDF"""
    
    # Create a BytesIO buffer to store PDF
    buffer = io.BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        textColor=colors.HexColor('#1e3c72'),
        alignment=1  # Center alignment
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        spaceAfter=12,
        textColor=colors.HexColor('#2c5282')
    )
    
    normal_style = ParagraphStyle(
        'Normal',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=6
    )
    
    # Story to hold PDF elements
    story = []
    
    # Title
    story.append(Paragraph("ENVIRONMENTAL PROTECTION AGENCY", title_style))
    story.append(Paragraph("COMPLIANCE MONITORING REPORT", title_style))
    story.append(Spacer(1, 20))
    
    # Header Information
    story.append(Paragraph(f"<b>Mining Operation:</b> {selected_mine}", normal_style))
    story.append(Paragraph(f"<b>Report Period:</b> {date_range[0].strftime('%B %d, %Y')} to {date_range[1].strftime('%B %d, %Y')}", normal_style))
    story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y %H:%M:%S')}", normal_style))
    story.append(Paragraph(f"<b>Generated by:</b> Guardian Ghana AI Monitoring System", normal_style))
    story.append(Spacer(1, 20))
    
    # Executive Summary
    story.append(Paragraph("EXECUTIVE SUMMARY", heading_style))
    
    summary_data = [
        ["Metric", "Value", "Status"],
        ["Overall Compliance Rate", f"{compliance_rate:.1f}%", 
         "✅ Within Limits" if compliance_rate >= 95 else "⚠️ Needs Attention" if compliance_rate >= 80 else "❌ Below Standard"],
        ["Average Turbidity", f"{avg_turbidity:.0f} NTU", 
         "✅ Normal" if avg_turbidity <= 100 else "⚠️ High" if avg_turbidity <= 150 else "❌ Critical"],
        ["Average pH Level", f"{avg_ph:.2f}", 
         "✅ Optimal" if 6.5 <= avg_ph <= 7.5 else "⚠️ Acceptable" if 6.0 <= avg_ph <= 8.5 else "❌ Critical"],
        ["Non-Compliance Incidents", str(incidents), 
         "✅ Excellent" if incidents == 0 else "⚠️ Attention Required" if incidents <= 3 else "❌ Immediate Action"],
    ]
    
    # Create table
    table = Table(summary_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3c72')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 20))
    
    # Detailed Compliance Data
    story.append(Paragraph("DETAILED COMPLIANCE METRICS", heading_style))
    
    # Calculate detailed metrics
    turbidity_compliance = (mining_data['Turbidity_NTU'] <= 100).mean() * 100
    ph_compliance = ((mining_data['pH'] >= 6.0) & (mining_data['pH'] <= 8.5)).mean() * 100
    do_compliance = (mining_data['Dissolved_Oxygen'] >= 5.0).mean() * 100
    
    detailed_data = [
        ["Parameter", "Standard", "Value", "Compliance Rate"],
        ["Turbidity (NTU)", "≤ 100 NTU", f"{avg_turbidity:.0f} NTU", f"{turbidity_compliance:.1f}%"],
        ["pH Level", "6.0 - 8.5", f"{avg_ph:.2f}", f"{ph_compliance:.1f}%"],
        ["Dissolved Oxygen", "≥ 5.0 mg/L", f"{mining_data['Dissolved_Oxygen'].mean():.2f} mg/L", f"{do_compliance:.1f}%"],
        ["Water Usage", "Report Only", f"{mining_data['Water_Usage_m3'].sum():,} m³", "N/A"],
    ]
    
    detailed_table = Table(detailed_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
    detailed_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5282')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    
    story.append(detailed_table)
    story.append(Spacer(1, 20))
    
    # Recommendations
    story.append(Paragraph("RECOMMENDATIONS & ACTIONS REQUIRED", heading_style))
    
    recommendations = []
    
    if compliance_rate < 95:
        recommendations.append("1. Increase monitoring frequency at non-compliant sites")
    
    if avg_turbidity > 100:
        recommendations.append("2. Implement additional sedimentation control measures")
    
    if incidents > 0:
        recommendations.append("3. Conduct root cause analysis for non-compliance incidents")
    
    if not recommendations:
        recommendations.append("1. Continue current monitoring and control practices")
    
    recommendations.append("2. Maintain automated reporting system")
    recommendations.append("3. Schedule quarterly equipment calibration")
    
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", normal_style))
    
    story.append(Spacer(1, 20))
    
    # Compliance Statement
    story.append(Paragraph("COMPLIANCE STATEMENT", heading_style))
    statement = f"""
    This report confirms that {selected_mine} has maintained an overall compliance rate of {compliance_rate:.1f}% 
    during the reporting period. All monitoring data has been collected and verified by the Guardian Ghana 
    AI Monitoring System in accordance with EPA guidelines.
    
    The data presented in this report is based on automated, real-time monitoring and represents 
    the most accurate and up-to-date compliance information available.
    """
    story.append(Paragraph(statement, normal_style))
    
    story.append(Spacer(1, 30))
    
    # Footer
    footer = Paragraph(
        "Generated by Guardian Ghana Environmental Monitoring Platform • guardian.ghana.tech@gmail.com • www.engchriss.github.io/guardianghana",
        ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=1
        )
    )
    story.append(footer)
    
    # Build PDF
    doc.build(story)
    
    # Get PDF data
    pdf_data = buffer.getvalue()
    buffer.close()
    
    return pdf_data


def generate_simple_pdf(selected_mine, compliance_rate, avg_turbidity, avg_ph, incidents):
    """Generate a simple PDF (fallback if reportlab fails)"""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height-50, "EPA Compliance Report")
    
    # Subtitle
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height-80, selected_mine)
    
    # Date
    c.setFont("Helvetica", 12)
    c.drawString(50, height-110, f"Report Date: {datetime.now().strftime('%Y-%m-%d')}")
    
    # Metrics
    y = height-150
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Compliance Summary:")
    
    c.setFont("Helvetica", 12)
    y -= 30
    c.drawString(70, y, f"• Compliance Rate: {compliance_rate:.1f}%")
    y -= 20
    c.drawString(70, y, f"• Average Turbidity: {avg_turbidity:.0f} NTU")
    y -= 20
    c.drawString(70, y, f"• Average pH: {avg_ph:.2f}")
    y -= 20
    c.drawString(70, y, f"• Non-Compliance Incidents: {incidents}")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Guardian Ghana AI Monitoring System")
    
    c.save()
    
    pdf_data = buffer.getvalue()
    buffer.close()
    
    return pdf_data


# === SIMULATED MINING DATA ===
def generate_mining_operations_data(mine_name, days=30):
    """Generate realistic mining operation data"""

    dates = [datetime.now().date() - timedelta(days=i) for i in range(days)]
    data = []

    for date in dates:
        # Base values with daily variation
        base_turbidity = np.random.randint(40, 120)
        base_ph = np.random.uniform(6.2, 7.5)
        base_do = np.random.uniform(4.5, 7.5)

        # Operational events (5% chance)
        if np.random.random() > 0.95:
            base_turbidity *= np.random.uniform(1.5, 3.0)
            base_ph -= np.random.uniform(0.5, 1.2)

        # Weekend effect (lower activity)
        if date.weekday() >= 5:
            base_turbidity *= 0.7
            base_do *= 1.1

        # Compliance calculation
        compliance = "🟢 Compliant"
        if base_turbidity > 100 or base_ph < 6.0 or base_do < 5.0:
            compliance = "🔴 Non-Compliant"
        elif base_turbidity > 70 or base_ph < 6.5 or base_do < 6.0:
            compliance = "🟡 Warning"

        data.append({
            "Date": date,
            "Turbidity_NTU": base_turbidity,
            "pH": round(base_ph, 2),
            "Dissolved_Oxygen": round(base_do, 2),
            "Compliance_Status": compliance,
            "Mine": mine_name,
            "Daily_Throughput": np.random.randint(50000, 150000),
            "Water_Usage_m3": np.random.randint(5000, 15000),
            "Treatment_Cost_GH₵": np.random.randint(5000, 20000)
        })

    return pd.DataFrame(data)


# Generate data
tarkwa_data = generate_mining_operations_data("Tarkwa Mine", 30)
damang_data = generate_mining_operations_data("Damang Mine", 30)

if selected_mine == "Both Operations":
    mining_data = pd.concat([tarkwa_data, damang_data])
else:
    mining_data = tarkwa_data if "Tarkwa" in selected_mine else damang_data

# === DASHBOARD ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header(f"📊 {selected_mine} - Environmental Performance")

# Key Metrics
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    compliance_rate = (mining_data['Compliance_Status'] == "🟢 Compliant").mean() * 100
    st.metric("Compliance Rate", f"{compliance_rate:.1f}%",
              delta=f"{(compliance_rate - 95):+.1f}%" if compliance_rate else None)

with col2:
    avg_turbidity = mining_data['Turbidity_NTU'].mean()
    st.metric("Avg Turbidity", f"{avg_turbidity:.0f} NTU",
              delta="-5 NTU" if avg_turbidity < 75 else "+5 NTU")

with col3:
    avg_ph = mining_data['pH'].mean()
    st.metric("Avg pH", f"{avg_ph:.2f}",
              delta="Optimal" if 6.5 <= avg_ph <= 7.5 else "Review")

with col4:
    incidents = (mining_data['Compliance_Status'] == "🔴 Non-Compliant").sum()
    st.metric("Non-Compliance Incidents", incidents, delta="This Month")

with col5:
    water_usage = mining_data['Water_Usage_m3'].sum()
    st.metric("Total Water Usage", f"{water_usage:,} m³", delta="Monthly")

st.markdown('</div>', unsafe_allow_html=True)

# === COMPLIANCE ANALYTICS ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("📈 Compliance Trend Analysis")

col1, col2 = st.columns(2)

with col1:
    # Compliance Trend Chart
    fig_compliance = px.line(mining_data, x='Date', y='Turbidity_NTU',
                             color='Mine' if selected_mine == "Both Operations" else None,
                             title='Turbidity Trend vs EPA Limit (100 NTU)',
                             labels={'Turbidity_NTU': 'Turbidity (NTU)', 'Date': 'Date'})

    # Add EPA limit line
    fig_compliance.add_hline(y=100, line_dash="dash", line_color="red",
                             annotation_text="EPA Limit", annotation_position="top right")

    st.plotly_chart(fig_compliance, use_container_width=True)

with col2:
    # pH Compliance Chart
    fig_ph = px.scatter(mining_data, x='Date', y='pH',
                        color='Compliance_Status',
                        title='pH Levels & Compliance Status',
                        labels={'pH': 'pH Level', 'Date': 'Date'},
                        color_discrete_map={
                            "🟢 Compliant": "green",
                            "🟡 Warning": "orange",
                            "🔴 Non-Compliant": "red"
                        })

    # Add pH range
    fig_ph.add_hrect(y0=6.0, y1=8.5, line_width=0, fillcolor="green", opacity=0.1,
                     annotation_text="EPA Range", annotation_position="top left")

    st.plotly_chart(fig_ph, use_container_width=True)

st.markdown('</div>', unsafe_allow_html=True)

# === DAILY TIME SAVINGS TRACKER ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("🔄 Daily Time Savings Tracker")

col1, col2 = st.columns(2)
with col1:
    st.metric("Manual Monitoring", "2.5 hours/day", "-")
with col2:
    st.metric("With Guardian Ghana", "30 minutes/day", "2 hours saved")

st.progress(0.2)
st.caption("Daily time reduction: 80%")
st.markdown('</div>', unsafe_allow_html=True)

# === ONE-CLICK EPA REPORTING WITH PDF ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("📄 One-Click EPA Compliance Reporting")

col_report1, col_report2 = st.columns(2)

with col_report1:
    if st.button("📊 Generate EPA Compliance Report (PDF)", type="primary", key="epa_pdf_report", use_container_width=True):
        with st.spinner("🔄 Generating professional EPA report..."):
            try:
                # Generate PDF
                pdf_data = generate_epa_pdf(
                    selected_mine, 
                    compliance_rate, 
                    avg_turbidity, 
                    avg_ph, 
                    incidents, 
                    mining_data
                )
                
                st.success("✅ Professional EPA report generated!")
                
                # Create download button for PDF
                b64 = base64.b64encode(pdf_data).decode()
                href = f'<a href="data:application/pdf;base64,{b64}" download="EPA_Compliance_Report_{selected_mine.replace(" ", "_")}_{datetime.now().date()}.pdf">📥 Download PDF Report</a>'
                st.markdown(href, unsafe_allow_html=True)
                
                # Show preview
                with st.expander("📄 Report Preview", expanded=True):
                    st.info("""
                    **Report Contents:**
                    1. Executive Summary
                    2. Compliance Metrics Table
                    3. Detailed Parameter Analysis
                    4. Recommendations
                    5. Compliance Statement
                    
                    **Features:**
                    • Professional formatting
                    • Color-coded status indicators
                    • EPA-ready format
                    • Company branding
                    
                    *This is a professionally formatted PDF ready for submission to EPA Ghana*
                    """)
                    
            except Exception as e:
                st.error(f"❌ Error generating PDF: {e}")
                st.info("Trying simplified PDF...")
                
                # Fallback to simple PDF
                try:
                    pdf_data = generate_simple_pdf(
                        selected_mine, 
                        compliance_rate, 
                        avg_turbidity, 
                        avg_ph, 
                        incidents
                    )
                    
                    b64 = base64.b64encode(pdf_data).decode()
                    href = f'<a href="data:application/pdf;base64,{b64}" download="EPA_Report_{selected_mine.replace(" ", "_")}.pdf">📥 Download Simplified PDF</a>'
                    st.markdown(href, unsafe_allow_html=True)
                except:
                    # Final fallback to text
                    report_content = f"""
                    EPA COMPLIANCE REPORT - {selected_mine}
                    Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

                    SUMMARY:
                    • Compliance Rate: {compliance_rate:.1f}%
                    • Avg Turbidity: {avg_turbidity:.0f} NTU
                    • Avg pH: {avg_ph:.2f}
                    • Non-Compliance Incidents: {incidents}
                    """
                    
                    st.download_button(
                        label="📥 Download Text Report",
                        data=report_content,
                        file_name=f"EPA_Report_{selected_mine.replace(' ', '_')}.txt",
                        mime="text/plain",
                        use_container_width=True
                    )

with col_report2:
    if st.button("📋 Quick Text Report", key="quick_text_report", use_container_width=True):
        st.success("✅ Quick report generated!")
        
        report_content = f"""
        EPA COMPLIANCE REPORT - {selected_mine}
        Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

        SUMMARY:
        • Compliance Rate: {compliance_rate:.1f}%
        • Avg Turbidity: {avg_turbidity:.0f} NTU
        • Avg pH: {avg_ph:.2f}
        • Non-Compliance Incidents: {incidents}

        RECOMMENDATIONS:
        1. Maintain current monitoring frequency
        2. Review turbidity levels at discharge points
        3. Continue automated reporting system

        Prepared by: Guardian Ghana AI Monitoring System
        """
        
        st.download_button(
            label="📥 Download Text Report",
            data=report_content,
            file_name=f"Quick_EPA_Report_{selected_mine.replace(' ', '_')}.txt",
            mime="text/plain",
            key="download_text_report",
            use_container_width=True
        )

# === DAILY TASK LIST ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("📋 Today's Monitoring Tasks")
tasks = [
    {"task": "Check pH levels at Point A", "status": "✅ Completed"},
    {"task": "Turbidity monitoring at Point B", "status": "⏳ In Progress"},
    {"task": "Generate weekly EPA report", "status": "📅 Scheduled"}
]
for t in tasks:
    st.write(f"{t['status']} {t['task']}")

st.markdown('</div>', unsafe_allow_html=True)

# === OPERATIONAL INTELLIGENCE ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("🤖 AI Operational Intelligence")

col1, col2 = st.columns(2)

with col1:
    st.subheader("🚨 Risk Predictions")

    # Simulated AI predictions
    risk_predictions = [
        {"Parameter": "Turbidity", "Risk Level": "Low", "Confidence": "85%",
         "Prediction": "Stable for next 72 hours"},
        {"Parameter": "pH", "Risk Level": "Medium", "Confidence": "72%",
         "Prediction": "Possible acidification in 48-72h"},
        {"Parameter": "Dissolved Oxygen", "Risk Level": "Low", "Confidence": "90%",
         "Prediction": "Optimal levels maintained"},
        {"Parameter": "Upstream Impact", "Risk Level": "High", "Confidence": "68%",
         "Prediction": "Illegal mining activity detected upstream"}
    ]

    for prediction in risk_predictions:
        if prediction["Risk Level"] == "High":
            st.error(f"**{prediction['Parameter']}**: {prediction['Prediction']}")
        elif prediction["Risk Level"] == "Medium":
            st.warning(f"**{prediction['Parameter']}**: {prediction['Prediction']}")
        else:
            st.success(f"**{prediction['Parameter']}**: {prediction['Prediction']}")

with col2:
    st.subheader("💰 Cost-Benefit Analysis")

    # ROI Calculation
    current_cost = mining_data['Treatment_Cost_GH₵'].mean()
    predicted_savings = current_cost * 0.25  # 25% savings

    st.metric("Current Monthly Treatment Cost", f"GH₵{current_cost:,.0f}")
    st.metric("Predicted Monthly Savings", f"GH₵{predicted_savings:,.0f}",
              delta="25% reduction")
    st.metric("Projected Annual Savings", f"GH₵{predicted_savings * 12:,.0f}")

    st.info("""
    **ROI Timeline:**
    • **3 months:** Payback period
    • **12 months:** 300% ROI
    • **24 months:** Full system automation
    
    **Savings Breakdown:**
    • Manual monitoring: GH₵15,000/month
    • Automated system: GH₵3,750/month
    • **Net savings: GH₵11,250/month**
    """)

st.markdown('</div>', unsafe_allow_html=True)

# === AUTOMATED REPORTS SECTION ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("🏛️ Automated Compliance Reporting")

report_types = [
    {"name": "Daily Operations Report", "frequency": "Daily", "format": "PDF", "action": "Generate Daily"},
    {"name": "Weekly Compliance Summary", "frequency": "Weekly", "format": "PDF/Excel", "action": "Generate Weekly"},
    {"name": "Monthly EPA Submission", "frequency": "Monthly", "format": "Official PDF", "action": "Generate Monthly"},
    {"name": "Quarterly Impact Assessment", "frequency": "Quarterly", "format": "PDF", "action": "Generate Quarterly"},
    {"name": "Annual Sustainability Report", "frequency": "Annually", "format": "PDF/PPT", "action": "Generate Annual"}
]

for i, report in enumerate(report_types):
    with st.expander(f"📋 {report['name']} ({report['frequency']})", expanded=False):
        col1, col2, col3 = st.columns([3, 2, 1])
        with col1:
            st.write(f"**Frequency:** {report['frequency']}")
            st.write(f"**Format:** {report['format']}")
            st.write(f"**Last Generated:** {datetime.now().date() - timedelta(days=np.random.randint(0, 7))}")
        with col2:
            st.write(f"**Next Due:** {datetime.now().date() + timedelta(days=np.random.randint(1, 30))}")
        with col3:
            if st.button(report['action'], key=f"gen_{i}"):
                st.success(f"✅ {report['name']} generated!")
                st.info(f"Check your downloads folder for the {report['format']} file.")

st.markdown('</div>', unsafe_allow_html=True)

# === ALERT SYSTEM ===
st.markdown('<div class="mining-section">', unsafe_allow_html=True)
st.header("🚨 Alert & Notification System")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Alert Configuration")

    alert_channels = st.multiselect(
        "Notification Channels:",
        ["Email", "SMS", "Telegram", "Dashboard", "Siren"],
        default=["Email", "Telegram", "Dashboard"],
        key="alert_channels"
    )

    alert_thresholds = st.slider(
        "Turbidity Alert Threshold (NTU):",
        min_value=50, max_value=150, value=80, step=5,
        key="turbidity_threshold"
    )

    st.number_input("pH Alert Range - Min:", min_value=4.0, max_value=7.0, value=6.0, step=0.1, key="ph_min")
    st.number_input("pH Alert Range - Max:", min_value=7.0, max_value=10.0, value=8.5, step=0.1, key="ph_max")

    if st.button("💾 Save Alert Settings", key="save_alerts"):
        st.success("✅ Alert settings saved!")

with col2:
    st.subheader("Recent Alerts")

    # Simulated alerts
    recent_alerts = [
        {"time": "2 hours ago", "type": "⚠️ Warning", "message": "Turbidity approaching limit: 85 NTU", "river": "Tarkwa Discharge"},
        {"time": "1 day ago", "type": "✅ Resolved", "message": "pH normalized to 7.2", "river": "Damang Outflow"},
        {"time": "3 days ago", "type": "🚨 Critical", "message": "Upstream illegal mining detected", "river": "Pra River"},
        {"time": "1 week ago", "type": "🔔 Info", "message": "Monthly EPA report generated", "river": "System"}
    ]

    for alert in recent_alerts:
        if "Critical" in alert["type"]:
            st.error(f"**{alert['type']}**: {alert['message']}")
            st.caption(f"📍 {alert['river']} • {alert['time']}")
        elif "Warning" in alert["type"]:
            st.warning(f"**{alert['type']}**: {alert['message']}")
            st.caption(f"📍 {alert['river']} • {alert['time']}")
        else:
            st.info(f"**{alert['type']}**: {alert['message']}")
            st.caption(f"📍 {alert['river']} • {alert['time']}")

st.markdown('</div>', unsafe_allow_html=True)

# === FOOTER ===
st.markdown("---")
st.markdown("""
<div style="text-align: center; padding: 2rem;">
    <h4>⛏️ Guardian Ghana Mining Portal</h4>
    <p>Professional EPA compliance reporting with AI-powered insights</p>
    <p>📞 Contact: guardian.ghana.tech@gmail.com | 🌐 https://engchriss.github.io/guardianghana</p>
    <p><small>© 2025 Guardian Ghana. All mining data is simulated for demonstration purposes.</small></p>
</div>
""", unsafe_allow_html=True)

# Export all data button
if st.button("📥 Export All Mining Data (CSV)", key="export_all_data", use_container_width=True):
    # Convert DataFrame to CSV string with proper encoding
    csv_string = mining_data.to_csv(index=False, encoding='utf-8')

    # Create download button with b64 encoding
    b64 = base64.b64encode(csv_string.encode()).decode()
    href = f'<a href="data:file/csv;base64,{b64}" download="goldfields_mining_data_{datetime.now().date()}.csv">📥 Download CSV File</a>'
    st.markdown(href, unsafe_allow_html=True)
    st.success("✅ Data exported successfully!")
